# Generated by Django 6.0.1 on 2026-02-03 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantiy',
            new_name='quantity',
        ),
    ]
